# Generated by Django 4.0.3 on 2022-06-18 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0011_auto_20220429_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfmodel',
            old_name='job_field',
            new_name='category',
        ),
    ]
